### ISSUE TITLE
UI enhancement 

### ISSUE THREAD

**Issue by UjjwalSharma01** [UjjwalSharma01/checklist#68]
Any enhancement of UI is welcome specially for the mobile version

**Comment by AnitSarkar123** [comment]
I will try ,Assign me under Apertre'24

**Comment by UjjwalSharma01** [comment]
Go Ahead @AnitSarkar123

**Comment by AnitSarkar123** [comment]
> Go Ahead @AnitSarkar123 

Sorry sir,i don't want to solve this issue at that time... because I want to add more features at that time...and many others add many features in the website.....for this reason please assign me this issue between 12th Jan to 14 Jan....if anyone want to contribute in it before 12 th Jan please assign him....at that time please unassigned me from this issue and give other issue to me....for this reason I write here "i will try"

**Comment by YooAshu** [comment]
@UjjwalSharma01 I want to work on this issue, pls assign me for this

**Comment by UjjwalSharma01** [comment]
Go ahead @YooAshu
